// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNetConnect() {
  return window['go']['system']['SystemService']['CheckNetConnect']();
}

export function ConfigGet(arg1) {
  return window['go']['system']['SystemService']['ConfigGet'](arg1);
}

export function ConfigGetBool(arg1) {
  return window['go']['system']['SystemService']['ConfigGetBool'](arg1);
}

export function ConfigSet(arg1, arg2) {
  return window['go']['system']['SystemService']['ConfigSet'](arg1, arg2);
}

export function CopyPath(arg1, arg2, arg3) {
  return window['go']['system']['SystemService']['CopyPath'](arg1, arg2, arg3);
}

export function GetPathDir(arg1) {
  return window['go']['system']['SystemService']['GetPathDir'](arg1);
}

export function GetPathExt(arg1) {
  return window['go']['system']['SystemService']['GetPathExt'](arg1);
}

export function GetPathFileName(arg1) {
  return window['go']['system']['SystemService']['GetPathFileName'](arg1);
}

export function GetSystemType() {
  return window['go']['system']['SystemService']['GetSystemType']();
}

export function GetSystemUserHomeDir() {
  return window['go']['system']['SystemService']['GetSystemUserHomeDir']();
}

export function OpenFileBrowser(arg1) {
  return window['go']['system']['SystemService']['OpenFileBrowser'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['system']['SystemService']['OpenURL'](arg1);
}

export function PathExists(arg1) {
  return window['go']['system']['SystemService']['PathExists'](arg1);
}

export function PathJoin(arg1) {
  return window['go']['system']['SystemService']['PathJoin'](arg1);
}

export function SelectDir(arg1) {
  return window['go']['system']['SystemService']['SelectDir'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['system']['SystemService']['SelectFile'](arg1, arg2);
}
