// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNetConnect():Promise<string>;

export function CheckUpdate():Promise<void>;

export function ConfigGet(arg1:string):Promise<any>;

export function ConfigGetBool(arg1:string):Promise<boolean>;

export function ConfigSet(arg1:string,arg2:string):Promise<void>;

export function GetSystemUserHomeDir():Promise<string>;

export function OpenFileBrowser(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SelectDir(arg1:string):Promise<string>;
