// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNetConnect() {
  return window['go']['system']['SystemService']['CheckNetConnect']();
}

export function CheckUpdate() {
  return window['go']['system']['SystemService']['CheckUpdate']();
}

export function ConfigGet(arg1) {
  return window['go']['system']['SystemService']['ConfigGet'](arg1);
}

export function ConfigGetBool(arg1) {
  return window['go']['system']['SystemService']['ConfigGetBool'](arg1);
}

export function ConfigSet(arg1, arg2) {
  return window['go']['system']['SystemService']['ConfigSet'](arg1, arg2);
}

export function GetSystemUserHomeDir() {
  return window['go']['system']['SystemService']['GetSystemUserHomeDir']();
}

export function OpenFileBrowser(arg1) {
  return window['go']['system']['SystemService']['OpenFileBrowser'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['system']['SystemService']['OpenURL'](arg1);
}

export function SelectDir(arg1) {
  return window['go']['system']['SystemService']['SelectDir'](arg1);
}
