// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateShell() {
  return window['go']['shell']['ShellManager']['CreateShell']();
}

export function CreateShellAndRunCmd(arg1, arg2, arg3) {
  return window['go']['shell']['ShellManager']['CreateShellAndRunCmd'](arg1, arg2, arg3);
}

export function Export(arg1) {
  return window['go']['shell']['ShellManager']['Export'](arg1);
}

export function RunCmd(arg1, arg2, arg3, arg4) {
  return window['go']['shell']['ShellManager']['RunCmd'](arg1, arg2, arg3, arg4);
}

export function RunCmdBySystem(arg1, arg2, arg3) {
  return window['go']['shell']['ShellManager']['RunCmdBySystem'](arg1, arg2, arg3);
}

export function StopShell(arg1) {
  return window['go']['shell']['ShellManager']['StopShell'](arg1);
}
