// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Move(arg1:string,arg2:string):Promise<string>;

export function ParseTreeData():Promise<Array<dto.TreeNode>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<string>;

export function WriteFileContent(arg1:string,arg2:string):Promise<string>;
