// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDir(arg1) {
  return window['go']['services']['ArticleTreeData']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['services']['ArticleTreeData']['CreateFile'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['services']['ArticleTreeData']['DeletePath'](arg1);
}

export function Move(arg1, arg2) {
  return window['go']['services']['ArticleTreeData']['Move'](arg1, arg2);
}

export function ParseTreeData() {
  return window['go']['services']['ArticleTreeData']['ParseTreeData']();
}

export function ReadFileContent(arg1) {
  return window['go']['services']['ArticleTreeData']['ReadFileContent'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['services']['ArticleTreeData']['Rename'](arg1, arg2);
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['services']['ArticleTreeData']['WriteFileContent'](arg1, arg2);
}
