// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCmd(arg1:string,arg2:string):Promise<string>;

export function StopCmd():Promise<string>;
