// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCmd(arg1, arg2) {
  return window['go']['services']['ShellService']['RunCmd'](arg1, arg2);
}

export function StopCmd() {
  return window['go']['services']['ShellService']['StopCmd']();
}
