// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateShell():Promise<number>;

export function CreateShellAndRunCmd(arg1:string,arg2:string,arg3:boolean):Promise<number>;

export function Export(arg1:services.NotifyShellData):Promise<void>;

export function RunCmd(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<string>;

export function RunCmdBySystem(arg1:string,arg2:string,arg3:number):Promise<string>;

export function StopShell(arg1:number):Promise<string>;
