// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFullPathToUrl(arg1) {
  return window['go']['services']['StaticServer']['ConvertFullPathToUrl'](arg1);
}

export function GetProjectStaticName() {
  return window['go']['services']['StaticServer']['GetProjectStaticName']();
}

export function GetStaticBaseUrl() {
  return window['go']['services']['StaticServer']['GetStaticBaseUrl']();
}

export function GetStaticFullDir() {
  return window['go']['services']['StaticServer']['GetStaticFullDir']();
}

export function GetStaticImagesFullDir() {
  return window['go']['services']['StaticServer']['GetStaticImagesFullDir']();
}

export function StartStaticServer(arg1) {
  return window['go']['services']['StaticServer']['StartStaticServer'](arg1);
}

export function UploadFile() {
  return window['go']['services']['StaticServer']['UploadFile']();
}
