// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFullPathToUrl(arg1:string):Promise<string>;

export function GetProjectStaticName():Promise<string>;

export function GetStaticBaseUrl():Promise<string>;

export function GetStaticFullDir():Promise<string>;

export function GetStaticImagesFullDir():Promise<string>;

export function StartStaticServer(arg1:string):Promise<void>;

export function UploadFile():Promise<void>;
