// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasNewVersion() {
  return window['go']['services']['UpdateService']['HasNewVersion']();
}

export function UpdateNewVersion() {
  return window['go']['services']['UpdateService']['UpdateNewVersion']();
}
