// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasNewVersion():Promise<boolean>;

export function UpdateNewVersion():Promise<void>;
