// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExistsVitepressDir(arg1:string):Promise<boolean>;

export function GetConfigPath():Promise<string>;

export function GetVpConfigData():Promise<string>;

export function RenameConfigName(arg1:string):Promise<void>;

export function ReplaceDefaultConfigContent(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;
