// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExistsVitepressDir(arg1) {
  return window['go']['vpsimpler']['VpConfig']['ExistsVitepressDir'](arg1);
}

export function GetConfigPath() {
  return window['go']['vpsimpler']['VpConfig']['GetConfigPath']();
}

export function GetVpConfigData() {
  return window['go']['vpsimpler']['VpConfig']['GetVpConfigData']();
}

export function RenameConfigName(arg1) {
  return window['go']['vpsimpler']['VpConfig']['RenameConfigName'](arg1);
}

export function ReplaceDefaultConfigContent(arg1, arg2) {
  return window['go']['vpsimpler']['VpConfig']['ReplaceDefaultConfigContent'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['vpsimpler']['VpConfig']['SaveConfig'](arg1);
}
