// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyTemplateFile(arg1) {
  return window['go']['vpsimpler']['VpManager']['CopyTemplateFile'](arg1);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['vpsimpler']['VpManager']['CreateProject'](arg1, arg2, arg3);
}

export function GetNodeVersion() {
  return window['go']['vpsimpler']['VpManager']['GetNodeVersion']();
}

export function GetNpmVersion() {
  return window['go']['vpsimpler']['VpManager']['GetNpmVersion']();
}
